### ISSUE TITLE
changes in Settings -> Desktop Effects -> yet-another-magic-lamp don't take effect

### ISSUE THREAD

**Issue by DArkErAsEr-BeAsT** [zzag/kwin-effects-yet-another-magic-lamp#10]
Hi, 
First of all i really love your minimize animation.
The problem is that per default the animation speed is a little bit too fast : so I wanted to slow it down and maybe change the resolution of the grid. However as it turns out none of the specified settings work, so i removed all the files and reinstalled the effect only to obtain exactly the same result. Do you have an idea what might be the cause of this ?

**Comment by zzag** [comment]
Argh, I forgot to rename https://github.com/zzag/kwin-effects-yet-another-magic-lamp/blob/master/src/kcm/YetAnotherMagicLampEffectKCM.cc#L48

**Comment by DArkErAsEr-BeAsT** [comment]
What did you forget to rename ?The line you indicated is the same on my machine

**Comment by zzag** [comment]
It should be kwin4_effect_yetanothermagiclamp.

**Comment by DArkErAsEr-BeAsT** [comment]
Ok thanks ! 

> It should be kwin4_effect_yetanothermagiclamp.
