### ISSUE TITLE
Build issue on openSUSE Leap 15.1

### ISSUE THREAD

**Issue by Nano-Ocelot** [zzag/kwin-effects-yet-another-magic-lamp#11]
I get this error when trying to compile the effect. I thought I had all dependencies, but I'm guessing I was wrong. Any help finding the pkg that supplies whatever 'epoxy' is would be appreciated. I can't find it with search engines.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find epoxy (missing: epoxy_LIBRARY epoxy_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/Findepoxy.cmake:53 (find_package_handle_standard_args)
  src/CMakeLists.txt:19 (find_package)

**Comment by trmdi** [comment]
Try installing missed dependences listed in  https://build.opensuse.org/package/view_file/home:trmdi/kwin-effects-yaml/kwin-effects-yaml.spec?expand=1

```bash
# zypper in libepoxy-devel
```

**Comment by Nano-Ocelot** [comment]
Well that let me finish making the build files, but then when I run 'make'
I get the following error.

[ 63%] Generating YetAnotherMagicLampConfig.h, YetAnotherMagicLampConfig.cpp
make[2]: *** No rule to make target '/org.kde.kwin.Effects.xml', needed by
'src/kcm/kwineffects_interface.cpp'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:240:
src/kcm/CMakeFiles/kwin_yetanothermagiclamp_config.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by trmdi** [comment]
No idea. Try removing the build directoruee and start from scratch?

**Comment by Nano-Ocelot** [comment]
Yeah, I tried that. Thanks though. Sorry for bothering you.

**Comment by trmdi** [comment]
I still you're missing some dependencies.
See this: https://github.com/zzag/kwin-effects-yet-another-magic-lamp/issues/2

**Comment by Nano-Ocelot** [comment]
I don't have that pkg in my default repos.

**Comment by Nano-Ocelot** [comment]
Nevermind. I installed dbus-1-devel and dbus-1-glib-devel. Was able to install it and the effect is in fact working! Thanks for the help and great work on this. It looks great.
