### ISSUE TITLE
Too dark window shadows

### ISSUE THREAD

**Issue by Kauramaito** [zzag/kwin-effects-yet-another-magic-lamp#15]
Big thanks for creating this beautiful effect! However there appears to be a small bug which causes window shadows to seem darker/stronger while the effect is running. It isn't really noticeable against dark wallpapers, but with lighter ones it is pretty apparent. This problem has persisted since the beginning and [switching the blend function](https://github.com/zzag/kwin-effects-yet-another-magic-lamp/commit/a7f84ad945ff8c87ef7399bef13f37102cd9fa13) back in January made it little less noticeable, but it definitely is still there.

Unfortunately I don't know how to approach this issue since I know nothing about OpenGL myself.

A quick comparison video:
Magic Lamp (default): https://imgur.com/a/pZjms00
Yet Another Magic Lamp: https://imgur.com/a/xubI74d

**Comment by zzag** [comment]
Please post output of

```sh
qdbus org.kde.KWin /KWin supportInformation
```

**Comment by Kauramaito** [comment]
Here is the output: https://pastebin.com/PxbZZw32

**Comment by zzag** [comment]
That's weird... No change in 5.17 comes to my mind that could somehow fix this bug.

Anyway, I close this issue because the reported bug has vanished.

**Comment by Kauramaito** [comment]
I was tweaking with the settings of this effect (duration, grid resolution etc) and after pressing "Defaults" -button this bug came back. I wish I could provide more meaningful insight to this issue, but there is again.

**Comment by Kauramaito** [comment]
I found the cause of the problem! Turns out something wonky happens when using "Yet Another Magic Lamp" with "Shapecorners" effect! Upgrading Plasma caused "Shapecorners" to get disabled which is why the issue appeared to vanish. This issue apparently has nothing to do with "Yet Another Magic Lamp".

Sorry about the confusion! And thanks for creating such a beautiful effect!

**Comment by zzag** [comment]
That's a great discovery!

> Upgrading Plasma caused "Shapecorners" to get disabled which is why the issue appeared to vanish.

Sounds sensible.
