### ISSUE TITLE
The effect is not supported since KWin 5.17?

### ISSUE THREAD

**Issue by trmdi** [zzag/kwin-effects-yet-another-magic-lamp#17]
After upgrading to Kwin 5.17 I don't see it in the Desktop Effect list.
Before that it worked.

```bash
$ qdbus-qt5 org.kde.KWin /Effects org.kde.kwin.Effects.listOfEffects | grep lamp
magiclamp
kwin4_effect_yetanothermagiclamp

$ qdbus-qt5 org.kde.KWin /Effects isEffectSupported kwin4_effect_yetanothermagiclamp
false

$ qdbus-qt5 org.kde.KWin /Effects isEffectSupported magiclamp
true
```

**Comment by zzag** [comment]
Try to recompile the effect. If my memory serves me well, the API version of libkwineffects got bumped in 5.17.

**Comment by zzag** [comment]
Also, I recommend you recompile the effect after each major release of KDE Plasma, i.e. after 5.17, 5.18, and so on.

**Comment by trmdi** [comment]
Ah sorry, it's my bad. That was because I still didn't get the latest package yet.
