### ISSUE TITLE
Use proper animation for left/top/right panels/docks

### ISSUE THREAD

**Issue by psifidotos** [zzag/kwin-effects-yet-another-magic-lamp#18]
When the taskmanager is at the left/right or top edge the animation used is not the proper one... It is still using the bottom direction animation instead of left/right and top direction animation accordingly.

**Comment by zzag** [comment]
Can you check the icon geometry? Most likely, the panel or the dock doesn't update the icon geometry.

**Comment by psifidotos** [comment]
@zzag it does, it works fine with the normal plasma effect

**Comment by psifidotos** [comment]
it is not the icon geometry the issue but rather the direction that the animation is applying

**Comment by psifidotos** [comment]
how to describe it better, for example for the left panel, the direction of the animation instead of being from right to left, it is from top to bottom, and the window is hidden in the top edge of the icon geometry instead of the right one
