### ISSUE TITLE
Problem when using with Plank dock (and some other problem too)

### ISSUE THREAD

**Issue by jdewfiez** [zzag/kwin-effects-yet-another-magic-lamp#20]
Okay, let me make it clear because I've been testing much more stuff with it.

This effect doesn't work with apps such as `systemsettings` and `kate`, I haven't tested all of them.

Also if a window placed lower than the top of the Plank dock, minimize it cause problems.

**Comment by zzag** [comment]
Plank sets rubbish icon geometries. There is not that much I can do about it.

I suggest to give a try to latte-dock.

**Comment by jdewfiez** [comment]
I switched to latte-dock now, it's much better than Plank. Thanks dude.
