### ISSUE TITLE
Fullscreen windows jumping above the panel

### ISSUE THREAD

**Issue by adarsh1001** [zzag/kwin-effects-yet-another-magic-lamp#22]
When minimizing or maximizing fullscreen windows, the window jumps above the top panel and then settles to its prescribed position. Video-
https://drive.google.com/file/d/14xTgBhPnOn-ofBbiXT23fiFk9Y88qKY7/view

I'm using latte-dock with a top panel on Ubuntu 19.10 with KDE 5.17.5. Output of `qdbus org.kde.KWin /KWin supportInformation` can be found at https://pastebin.com/jAkc4tjX

**Comment by zzag** [comment]
Heh, this is intentional behavior. :D

**Comment by adarsh1001** [comment]
It didn't used to do that when I was on KDE 5.17.4. Any way to stop it from jumping above the top panel (like the default magic lamp)? 😅

**Comment by zzag** [comment]
Unfortunately, no. YAML will bump a window only if the window and its icon in the task manager overlap.

You could set the bump distance to 0, but it's not possible to disable winodw bumping altogether.
