### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by Nasdrovia69** [zzag/kwin-effects-yet-another-magic-lamp#38]
Sorry i tried to install on Fedora 33 Kde but don't work i join output here
[error.txt](https://github.com/zzag/kwin-effects-yet-another-magic-lamp/files/6217104/error.txt)
thank's  if you can explain me what's wrong

**Comment by zzag** [comment]
It seems like you building the effect against < Plasma 5.20. Please checkout `Plasma/5.20` branch.
