### ISSUE TITLE
Effect is unable to be built on Pop! 21.04

### ISSUE THREAD

**Issue by pahaze** [zzag/kwin-effects-yet-another-magic-lamp#42]
Hello, hopefully things are going good at the time of reading. I just upgraded my install of Pop! 20.04 to 21.04 and KDE was upgraded alongside it. The effect worked great on 20.04 and had no issues, however, now it does not work. I thought this was just a fault of mine or that it needed to be rebuilt due to the upgrade, so I went to rebuild it. I re-cloned, made the build dir, aaaaaaaaand...

![unbuildable-console](https://user-images.githubusercontent.com/69173292/124070280-90934c80-da0b-11eb-9e31-fad725cc1fbc.png)

Missing header file? (Full paste is [here](https://pastebin.com/0yS1zwfZ)) 

This could be a fault of mine, however, I did not face this issue before upgrading to 21.04, and searching on DuckDuckGo or Google for the file being missing (kwindeformeffect.h) doesn't really help. I absolutely adore this effect because of how good it is. 

I'm not sure what you would need from system information (if any, really), however, just incase, I am on KDE Plasma 5.21.4 (KWin also 5.21.4), Qt 5.15.2, KDE Frameworks 5.80.0, my Linux kernel is version 5.11.0-7620-generic, and all needed things from the README are installed for Ubuntu and fully updated. Any help with this is gladly appreciated, I don't like seeing a window just appear or disappear (lol), and thank you for your time reading this.

**Comment by trmdi** [comment]
It seems the master branch is for the next version of Plasma. So what branch is for the current Plasma?

**Comment by pahaze** [comment]
> It seems the master branch is for the next version of Plasma. So what branch is for the current Plasma?

OHHHH... I misread 5.21 as 5.12... My bad 😅... I'll close the issue and reopen if needed. Thank you!
