### ISSUE TITLE
Stop working after KDE Plasma updated to version 5.22.3 ( Manjaro KDE Plasma version)

### ISSUE THREAD

**Issue by QuakeString** [zzag/kwin-effects-yet-another-magic-lamp#44]
I used to use this extension for long time. but today after update of Plasma to 5.22.3 this efffect stop working.
even though its compiling successfully. 
here is my system detail

![image](https://user-images.githubusercontent.com/5375918/125500641-aad56ddc-2d0e-422d-8463-c79a82cfc575.png)

**Comment by zzag** [comment]
Did you build the effect manually? if so, what branch did you build it from?

**Comment by QuakeString** [comment]
> Did you build the effect manually? if so, what branch did you build it from?

I try i from AUR and then try it as instructed here in github page. Both attempt failed. The effect does not appear on kde settings effect page.

**Comment by zzag** [comment]
Can you please run kwin as `env QT_LOGGING_RULES="kwin_core.debug=true" kwin_x11 --replace` and post the output here?

**Comment by zzag** [comment]
> i just get error when I try to build manually

master builds only with Plasma 5.23. You need to checkout `Plasma/5.22` branch.

**Comment by QuakeString** [comment]
> > i just get error when I try to build manually
> 
> master builds only with Plasma 5.23. You need to checkout `Plasma/5.22` branch.
> 
> edit: I added the checkout step in README file

Followed updated instruction. It worked. Thank you.
