### ISSUE TITLE
Kubuntu 20.04 LTS KFConfig configuration files were considered but not accepted

### ISSUE THREAD

**Issue by ybgirgin3** [zzag/kwin-effects-yet-another-magic-lamp#46]
## Kubuntu 20.04 LTS version still uses Plasma 5.19 and you guys doesn't have branch for 5.19

``sh
CMake Warning at /usr/local/share/ECM/find-modules/FindKF5.cmake:53 (find_package):
  Could not find a configuration file for package "KF5Config" that is
  compatible with requested version "5.78".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake, version: 5.68.0
    /lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake, version: 5.68.0

Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

-- Could NOT find KF5Config , checked the following files:
    /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (version 5.68.0)
    /lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (version 5.68.0)

CMake Warning at /usr/local/share/ECM/find-modules/FindKF5.cmake:53 (find_package):
  Could not find a configuration file for package "KF5ConfigWidgets" that is
  compatible with requested version "5.78".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake, version: 5.68.0
    /lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake, version: 5.68.0

Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

-- Could NOT find KF5ConfigWidgets , checked the following files:
    /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (version 5.68.0)
    /lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (version 5.68.0)

CMake Warning at /usr/local/share/ECM/find-modules/FindKF5.cmake:53 (find_package):
  Could not find a configuration file for package "KF5CoreAddons" that is
  compatible with requested version "5.78".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.68.0
    /lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake, version: 5.68.0

Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

-- Could NOT find KF5CoreAddons , checked the following files:
    /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (version 5.68.0)
    /lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (version 5.68.0)

CMake Warning at /usr/local/share/ECM/find-modules/FindKF5.cmake:53 (find_package):
  Could not find a configuration file for package "KF5WindowSystem" that is
  compatible with requested version "5.78".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake, version: 5.68.0
    /lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake, version: 5.68.0

Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)

-- Could NOT find KF5WindowSystem , checked the following files:
    /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (version 5.68.0)
    /lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (version 5.68.0)

CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find KF5 (missing: Config ConfigWidgets CoreAddons WindowSystem)
  (Required is at least version "5.78")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:94 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/berkay/Genel/kwin-effects-yet-another-magic-lamp/build/CMakeFiles/CMakeOutput.log".
``

**Comment by zzag** [comment]
If it's Plasma 5.19, you need to build the effect from `Plasma/5.20` branch. It's a bit confusing, but `Plasma/5.20` builds with plasma 5.20 and earlier, e.g. 5.19.

```
git clone https://github.com/zzag/kwin-effects-yet-another-magic-lamp.git --branch Plasma/5.20

# run cmake and make as usual
```

**Comment by ybgirgin3** [comment]
Thanks that worked :)
