### ISSUE TITLE
Doesn't work on Plasma 5.23.3

### ISSUE THREAD

**Issue by gianmarcogg03** [zzag/kwin-effects-yet-another-magic-lamp#52]
I have updated to Plasma 5.23.3 on Arch and the effect doesn't work anymore and it won't even appear in the list of desktop effects in the System Settings.

**Comment by keyb0ardninja** [comment]
Can confirm, same problem here.

**Comment by zzag** [comment]
You need to rebuild the effect.

**Comment by gianmarcogg03** [comment]
May you kindly fix also the sliding effect for the notifications? It broke on 5.23 as well.

**Comment by zzag** [comment]
It should be also fixed by rebuilding the effect. I bumped pkgrel some time ago to trigger a rebuild but it seems like some people updated it while running plasma 5.22.
