### ISSUE TITLE
Fails to build on kde 5.24 beta

### ISSUE THREAD

**Issue by angrylinuxuser** [zzag/kwin-effects-yet-another-magic-lamp#55]
-- The C compiler identification is GNU 11.1.0
-- The CXX compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:30 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5Config: /usr/lib64/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.90.0") 
-- Found KF5ConfigWidgets: /usr/lib64/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.90.0") 
-- Found KF5CoreAddons: /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.90.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found KF5WindowSystem: /usr/lib64/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.90.0") 
-- Found KF5: success (found suitable version "5.90.0", minimum required is "5.78") found components: Config ConfigWidgets CoreAddons WindowSystem 
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use
  Findkwineffects.cmake
Call Stack (most recent call first):
  cmake/Modules/Findkwineffects.cmake:69 (ecm_find_package_version_check)
  CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found kwineffects_kwineffects: /usr/lib/libkwineffects.so (found version "") 
-- Found kwineffects_kwinglutils: /usr/lib/libkwinglutils.so (found version "") 
-- Found kwineffects: /usr/lib/libkwineffects.so;/usr/lib/libkwinglutils.so  found components: kwineffects kwinglutils 
-- Found epoxy: /usr/lib/libepoxy.so (found version "1.5.9") 
-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.90.0)
 * KF5Codecs (required version >= 5.90.0)

-- The following REQUIRED packages have been found:

 * ECM (required version >= 5.78)
 * Qt5
 * Qt5DBus (required version >= 5.15.2)
 * KF5Config (required version >= 5.90.0)
 * KF5ConfigWidgets (required version >= 5.78)
 * Qt5Core (required version >= 5.15.2)
 * KF5CoreAddons (required version >= 5.78)
 * Qt5Gui (required version >= 5.15.2)
 * KF5WindowSystem (required version >= 5.78)
 * KF5 (required version >= 5.78)
 * kwineffects
 * KWinDBusInterface
 * epoxy

-- Configuring done
-- Generating done
-- Build files have been written to: /home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/build
[  5%] Automatic MOC for target kwin_yetanothermagiclamp_config
[ 10%] Automatic MOC for target kwin4_effect_yetanothermagiclamp
AutoMoc warning
---------------
"SRC:/src/plugin.cc"
includes the moc file "plugin.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/plugin.cc"
into
  "BIN:/src/kwin4_effect_yetanothermagiclamp_autogen/include/plugin.moc"
included by
  "SRC:/src/plugin.cc"

Command
-------
/usr/bin/moc -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -Dkwin4_effect_yetanothermagiclamp_EXPORTS -I/home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/build/src -I/home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src -I/usr/include/qt -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ -I/usr/include/qt/QtGui -I/usr/include/KF5/KConfigCore -I/usr/include/KF5 -I/usr/include/KF5/KConfigGui -I/usr/include/qt/QtXml -I/usr/include/KF5/KCoreAddons -I/usr/include/KF5/KWindowSystem -I/usr/include/qt/QtWidgets -I/usr/include -I/usr/include/c++/11.1.0 -I/usr/include/c++/11.1.0/x86_64-pc-linux-gnu -I/usr/include/c++/11.1.0/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/include-fixed --include /home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/build/src/kwin4_effect_yetanothermagiclamp_autogen/moc_predefs.h --output-dep-file -o /home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/build/src/kwin4_effect_yetanothermagiclamp_autogen/include/plugin.moc /home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/plugin.cc

Output
------
/home/remaros/.cache/paru/clone/kwin-effects-yet-another-magic-lamp-git/src/kwin-effects-yet-another-magic-lamp-git/src/plugin.cc:21: Parse error at "FILE"

make[2]: *** [src/CMakeFiles/kwin4_effect_yetanothermagiclamp_autogen.dir/build.make:71: src/CMakeFiles/kwin4_effect_yetanothermagiclamp_autogen] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:386: src/CMakeFiles/kwin4_effect_yetanothermagiclamp_autogen.dir/all] Błąd 2
make[1]: *** Oczekiwanie na niezakończone zadania....
[ 10%] Built target kwin_yetanothermagiclamp_config_autogen
make: *** [Makefile:146: all] Błąd 2

**Comment by zzag** [comment]
Should be fixed now.
