### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by bluebyt65** [zzag/kwin-effects-yet-another-magic-lamp#64]
Error while installing on Archlinux KDE 5.26.

[Link](https://pastebin.com/eLrD87Ji)

**Comment by zzag** [comment]
```
branch 'Plasma/5.23' set up to track 'origin/Plasma/5.23'.
Switched to a new branch 'Plasma/5.23'
```

it looks you try to build this effect for 5.23. Make sure that you checked out `Plasma/5.26`

**Comment by bluebyt65** [comment]
My bad! Its working now, I will close this.
