### ISSUE TITLE
wrong drawing, when there are two screens

### ISSUE THREAD

**Issue by lmca2000** [zzag/kwin-effects-yet-another-magic-lamp#7]
first of all, congratulate them for the great work of this effect, it is excellent, but not free of errors.

this happens when an extra screen is connected or disconnected, the effect loses the original drawing.

**Comment by zzag** [comment]
What do you mean by original drawing?

**Comment by lmca2000** [comment]
> What do you mean by original drawing?
in this image, I disconnected a screen, and the effect looks like this.
![TwoScreen](https://user-images.githubusercontent.com/20801459/57178744-32767900-6e43-11e9-8d98-355e31b7c461.png)

**Comment by zzag** [comment]
Can you post "before" screenshot?

**Comment by lmca2000** [comment]
> Can you post "before" screenshot?

Before
![TwoScreenConected](https://user-images.githubusercontent.com/20801459/57178994-b8e08a00-6e46-11e9-8171-847db06bc263.png)

After
![TwoScreenDisonectedExtra](https://user-images.githubusercontent.com/20801459/57178998-c1d15b80-6e46-11e9-8c29-72c9ee3206ef.png)
The image of the previous post, no longer appears with those waves, since I reinstalled the lamp effect.

**Comment by zzag** [comment]
Hmm, looks like there are issues with provided icon geometry. If that's the case, it should be addressed in plasmashell and not this effect.

Can you post output of xprop before and after disconnecting the second screen? (you need to run xprop from terminal and click the dolphin window)

**Comment by lmca2000** [comment]
Thanks for the guide, I will be asking in the lists of kde neon.
