### ISSUE TITLE
When activating blur effect and lamp effect together, it causes problems.

### ISSUE THREAD

**Issue by lmca2000** [zzag/kwin-effects-yet-another-magic-lamp#8]
When activating blur effect and lamp effect together, although the lamp effect does not stop working, the blur effect is blocked in an image but with a huge zoom. and on the other hand the lamp effect minimizing produces like a white window before minimizing.

**Comment by zzag** [comment]
> the blur effect is blocked in an image but with a huge zoom

Hmm, you say that background behind windows is not blurred when this effect is active, right? If so, then this is intended behavior.

> on the other hand the lamp effect minimizing produces like a white window before minimizing.

This effect uses mipmaps to smooth textures, so that's sort of intended behavior as well. FWIW, this issue is noticeable only with high animation duration values.

**Comment by lmca2000** [comment]
> > the blur effect is blocked in an image but with a huge zoom
> 
> Hmm, you say that background behind windows is not blurred when this effect is active, right? If so, then this is intended behavior.

That the blur effect is deactivated while minimizing, it is not inconvenient, I do not have an image at this moment to explain myself better. But apparently it has an error and the transparent windows and with the blur effect, it shows another image that is not the one of the bottom of it.

> 
> > on the other hand the lamp effect minimizing produces like a white window before minimizing.
> 
> This effect uses mipmaps to smooth textures, so that's sort of intended behavior as well. FWIW, this issue is noticeable only with high animation duration values.

It is with the default values. the truth to that if it would be difficult to take a picture.

**Comment by zzag** [comment]
> But apparently it has an error and the transparent windows and with the blur effect, it shows another image that is not the one of the bottom of it.

Can you post a screenshot of it?

**Comment by lmca2000** [comment]
I have compiled the lamp effect again, and so far I have not had that error, so for the moment, it is perfect, thanks for the willingness to help.
