### ISSUE TITLE
Doesn't work anymore in Plasma 5.16

### ISSUE THREAD

**Issue by krisives** [zzag/kwin-effects-yet-another-magic-lamp#9]
After upgrading to KDE Plasma 5.16.0 in Neon User it doesn't show the effect anymore in the Desktop Effects menu.

**Comment by zzag** [comment]
You need to recompile the effect.

**Comment by krisives** [comment]
The effect is automatically built on Launchpad via a recipe in the Disco repos. Does this mean the ABI changed again for kwin effects?

**Comment by zzag** [comment]
Yes.
